app/models.py
import bson
from flask.ext.login import UserMixin
from . import db, lm


@lm.user_loader
def load_user(uid):
    return User.query(bson.objectid.ObjectId(str(uid)))


class User(UserMixin, db.Document):
    username = db.StringField(required=True, max_length=15)
    email = db.StringField(max_length=40)
    password = db.StringField(max_length=15)
    avatar = db.FileField()

    @property
    def is_active(self):
        return True

    @property
    def is_authenticated(self):
        return True

    @property
    def is_anonymous(self):
        # False as we do not support annonymity
        return False

    @staticmethod
    def query(uid):
        result = User.objects(id=uid)
        if len(result) != 0:
            value = result[0]
            return value
        else:
            return None

    def verify_password(self, pswd):
        if self.password == pswd:
            return True
        return False


class Profile(db.Document):
    user = db.ReferenceField(User)
    location = db.StringField(max_length=100)
    education = db.StringField(max_length=50)
    job = db.StringField(max_length=30)
    position = db.StringField(max_length=30)
    bio = db.StringField(max_length=50)


class Post(db.Document):
    """docstring for Post"""
    user = db.ReferenceField(User)
    title = db.StringField(max_length=50)
    tag = db.ListField()
    body = db.StringField(max_length=10000)
    preview = db.StringField(max_length=200)
    date = db.DateTimeField()


class Comment(db.Document):
    """docstring for Comments"""
    post = db.ReferenceField(Post)
    commenter = db.StringField(max_length=20)
    content = db.StringField(max_length=200)
    date = db.DateTimeField()


class Stared(db.Document):
    """docstring for Stared"""
    user = db.ReferenceField(User)
    stared = db.ListField()


class Starring(db.Document):
    """docstring for Starring"""
    user = db.ReferenceField(User)
    starring = db.ListField()


class Liked(db.Document):
    """docstring for Likeed"""
    post = db.ReferenceField(Post)
    liked = db.ListField()


class Liking(db.Document):
    """docstring for Liking"""
    user = db.ReferenceField(User)
    liking = db.ListField()

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.mail import Mail
from flask.ext.moment import Moment
from flask_mongoengine import MongoEngine, MongoEngineSessionInterface
from flask.ext.login import LoginManager
from flaskext.markdown import Markdown
from flask.ext.pagedown import PageDown
from config import config

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = MongoEngine()
pagedown = PageDown()
lm = LoginManager()
lm.session_protection = 'strong'
lm.login_view = 'auth.login'


def createApp(name):
    app = Flask(__name__)
    app.config.from_object(config[name])

    lm.init_app(app)
    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    app.session_interface = MongoEngineSessionInterface(db)
    Markdown(app)
    pagedown.init_app(app)

    from .main import main as mainBluePrint
    app.register_blueprint(mainBluePrint)

    from .auth import auth as authBluePrint
    app.register_blueprint(authBluePrint)

    from .settings import setting as settingBluePrint
    app.register_blueprint(settingBluePrint, url_prefix='/setting')

    from .api_v_1_0 import api as apiBluePrint
    app.register_blueprint(apiBluePrint, url_prefix='/api')

    return app

app/api_v_1_0/__init__.py
from flask import Blueprint
api = Blueprint('api',__name__)

from . import views

app/api_v_1_0/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2016-09-05 15:28:20
# @Author  : Wangmengcn (eclipse_sv@163.com)
# @Link    : https://eclipsesv.com
# @Version : $Id$

from flask.ext.login import current_user, login_required
from flask import jsonify

from . import api
from . import githubData


@api.route('/user')
@login_required
def getUserinfo():
    if current_user.username is not None:
        username = current_user.username
        baseicdata = githubData.getBasicInfo(username)
        return jsonify(baseicdata)

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import mainview, errorViews

app/settings/__init__.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2016-08-18 15:33:56
# @Author  : Wangmengcn (eclipse_sv@163.com)
# @Link    : https://eclipsesv.com
# @Version : $Id$

from flask import Blueprint

setting = Blueprint("setting", __name__)

from . import view

app/templates/article.html
{% extends "base.html" %}
{% block head%}
{{super()}}
<link rel="stylesheet" href="../static/css/md.css" />
{% endblock%}
{% block content %}
{{ super() }}
<div class="container">
	{%if current_user.is_authenticated%}
		{%if post%}
			<div class="panel panel-success">
				<div class="panel-heading">
					<h3 class="panel-title"><a href="https://localhost:5000/post/{{post.title}}">{{post.title}}</a></h3>
					<br>
					<h4>{{current_user.username}} wrote at {{post.date}}</h4>
					</div>
					<div class="panel-body">
					{{ post.body | markdown }}
				</div>
			</div>
			<h4> 	<strong>评论区</strong> </h4>
			{%if comments%}
				{%for comment in comments%}
					<div class="panel panel-default">
						<div class="panel-heading">{{comment.commenter}}</div>
						<div class="panel-body">
							{{comment.content}}						
						</div>
					</div>
				{%endfor%}
			{%else%}
			<h5>暂无评论</h5>
			{%endif%}
			<form action="{{url_for('main.getComment',title=post.title)}}" method="post">
				<div class="panel panel-info">
					<div class="panel-heading">添加评论</div>
					<div class="panel-body">
						<div class="input-group input-group-lg" id="commnet-input">
						  <textarea name="comment" id="comment-area" cols="30" rows="10"></textarea>
						</div>					
					</div>
				</div>
				<div>
					<input type="submit" name="submit" value="评论" style="padding: 5px; float:left">
				</div>
			</form>
		{%else%}
			<h2>还没有发表过文章，<a href="{{url_for('main.posts')}}">去写一篇</a> </h2>
		{%endif%}
	{%else%}
		<h2>还未登陆，<a href="{{url_for('auth.login')}}">去登陆</a></h2>
	{%endif%}
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{%block title%}Mygit{%endblock%}

{% block head %} 
{{ super() }}
<link rel="stylesheet" type="text/css" href="../static/css/bootstrap.css">
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<script src="../static/js/Douyufanjquery.min.js"></script>
<script src="../static/js/bootstrap.min.js"></script>
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.main_index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.main_index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.posts') }}">Posts</a></li>
                {% endif %}
                <li><a href="{{url_for('api.getUserinfo')}}">User</a> </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img style="height:20px" src="https://o3sw4xojp.qnssl.com/c66cb2fb1e610a03bbebf258fb3210f1.jpg">
                    </a>
                    <ul class="dropdown-menu">
                        <p style="padding:3px 20px">Login in as {{current_user.username}}</p>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('setting.password_reset_request') }}">Your profile</a></li>
                        <li><a href="{{ url_for('setting.personal_setting') }}">Settings</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert"></button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
{{ super() }}
<div class="container">
	{%if current_user.is_authenticated%}
		{%if posts%}
			{%for post in posts%}
				<div class="panel panel-default">
				  <div class="panel-heading">
				    <h3 class="panel-title"><a href="https://localhost:5000/post/{{post.title}}">{{post.title}}</a></h3>
				  	<br>
		  			<h4>{{current_user.username}} wrote at {{post.date}}</h4>
				  </div>
				  <div class="panel-body">
				    {{ post.preview | markdown }}
				  </div>
				  <div class="panel-footer"><a href="https://localhost:5000/post/{{post.title}}">阅读全文</a></div>
				</div>					
			{%endfor%}
		{%else%}
			<h2>还没有发表过文章，<a href="{{url_for('main.posts')}}">去写一篇</a> </h2>
		{%endif%}
	{%else%}
		<h2>还未登陆，<a href="{{url_for('auth.login')}}">去登陆</a></h2>
	{%endif%}
</div>
{% endblock %}
<html>
    <head>
        <title>OAuth Flask Demo</title>
    </head>
    <body>
        <h1>OAuth Demo</h1>
        {% for message in get_flashed_messages() %}
            <p>{{ message }}</p>
        {% endfor %}
        {% if current_user.is_authenticated %}
            <h2>Hi, {{ current_user.username }}!</h2>
            <img src="{{current_user.avatar_url}}" alt="">
            <a href="{{current_user.html_url}}"></a>
            <p><a href="{{ url_for('auth.logout') }}">Logout</a></p>
        {% else %}
            <h2>I don't know you!</h2>
            <p><a href="{{ url_for('auth.oauth_authorize',provider='Github') }}">Login with Facebook</a></p>
            <p><a href="{{ url_for('auth.oauth_authorize', provider='twitter') }}">Login with Twitter</a></p>
        {% endif %}
    </body>
</html>

app/templates/posts.html
<html>
	<head>
		
	</head>
	<body>
		
	</body>
</html>
{%extends "base.html"%}
{%block head%}
{{super()}}
<link rel="stylesheet" href="../static/css/editormd.min.css" />
<link rel="stylesheet" href="../static/css/style.css" />
{%endblock%}
{%block page_content%}
<form action="{{url_for('main.posts')}}" method="post">
	<div class="input-group input-group-lg" style="width:100%">
	  <input type="text" class="form-control" placeholder="Input your title" aria-describedby="sizing-addon1" name="post_title">
	</div>
	<div class="layout">
		<div id="editormd">
		    <textarea style="display:none;">### 用markdown写下你的想法吧 !</textarea>
		</div>
	</div>
	<div style="width:90%;margin: 10px auto;">
        <input type="submit" name="submit" value="Publish" style="padding: 5px; float:left"> 
    </div>
</form>

		
	<script src="../static/js/Douyufanjquery.min.js"></script>
	<script src="../static/editormd.min.js"></script>
	<script type="text/javascript">
	    $(function() {
	        var editor = editormd("editormd", {
	            path : "../static/lib/" 
	        });        
	    });
	</script>
{%endblock%}

app/templates/profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Mygit - Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/settings/resetemil.html
{% extends "settings/setting.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Mygit - Rest Email{% endblock %}

{% block setting %}
<div class="page-header">
    Reset Email
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/settings/resetpsw.html
{% extends "settings/setting.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% block title %}Mygit - Rest Password{% endblock %}

{% block setting %}
<div class="page-header">
    Reset Password
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/settings/setting.html
{% extends "base.html" %}
{% block head %} 
{{ super() }}
<link rel="stylesheet" type="text/css" href="../static/css/md.css">
{% endblock %}
{% block content %}
{{ super() }}
<div class="container" id="setting">
	<div class="panel panel-default" id="setting-panel">
		<div class="panel-heading">Personal settings</div>
		<ul class="list-group">
			<li class="list-group-item">
				<a href="{{url_for('setting.password_reset_request')}}">Reset Password</a>
			</li>
			<li class="list-group-item">
				<a href="{{url_for('setting.email_reset_request')}}">Reset Email</a>
			</li>
		</ul>
	</div>
	<div class="panel panel-default" id="content-panel">
		{% block setting%}
		{% endblock %}
	</div>
</div>
{% endblock %}